"""initial

Revision ID: 354ab969e4cf
Revises: 
Create Date: 2026-05-11 21:01:06.097623

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '354ab969e4cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('seniority', sa.String(length=50), nullable=False),
    sa.Column('experience_required', sa.String(length=100), nullable=False),
    sa.Column('work_mode', sa.String(length=50), nullable=False),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tech_match_score', sa.Float(), nullable=False),
    sa.Column('trajectory_score', sa.Float(), nullable=False),
    sa.Column('competition_score', sa.Float(), nullable=False),
    sa.Column('red_flag', sa.Boolean(), nullable=False),
    sa.Column('founding_signal', sa.Boolean(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('still_active', sa.Boolean(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('canonical_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_canonical_id', ['canonical_id'], unique=False)
        batch_op.create_index('ix_jobs_founding_signal', ['founding_signal'], unique=False)
        batch_op.create_index('ix_jobs_posted_date', ['posted_date'], unique=False)
        batch_op.create_index('ix_jobs_red_flag', ['red_flag'], unique=False)
        batch_op.create_index('ix_jobs_source', ['source'], unique=False)
        batch_op.create_index('ix_jobs_still_active', ['still_active'], unique=False)
        batch_op.create_index('ix_jobs_tech_match_score', ['tech_match_score'], unique=False)
        batch_op.create_index('ix_jobs_trajectory_score', ['trajectory_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_trajectory_score')
        batch_op.drop_index('ix_jobs_tech_match_score')
        batch_op.drop_index('ix_jobs_still_active')
        batch_op.drop_index('ix_jobs_source')
        batch_op.drop_index('ix_jobs_red_flag')
        batch_op.drop_index('ix_jobs_posted_date')
        batch_op.drop_index('ix_jobs_founding_signal')
        batch_op.drop_index('ix_jobs_canonical_id')

    op.drop_table('jobs')
    # ### end Alembic commands ###
